### ISSUE TITLE
Table Sorting

### ISSUE THREAD

**Issue by Visionz1** [adriweb/EEPro-for-Nspire#5]
Hi adriweb,

I recently found your EEPro code for the Nspire and have really enjoyed it. I have been trying to reverse engineer the code and understand and have successfully added some additional functions. Although I can not figure out a way to get the variables on the left side of the screen to be listed in alphabetical order or figure out what is determining the order they appear. As of right now it seems the variables get jumbled and I would like to be able to sort them in a more logical way. Any help would be appreciated as I am not super experienced in lua.

**Comment by Visionz1** [comment]
This is what I am referring too
![image](https://user-images.githubusercontent.com/18312070/200186275-26d20a7c-fe3a-4ebf-bf19-3f24b42614f8.png)

**Comment by adriweb** [comment]
Sorry this project isn't being worked on anymore, and it's been many years so I wouldn't remember.
Maybe @jimbauwens knows?

After a quick look, maybe you just need to sort the table before using pairs on it: https://github.com/adriweb/EEPro-for-Nspire/blob/master/2%20-%20%20FormulaPro/2%20-%20FPGui.lua#L198

edit: well, sorting and storing the key-values in a numerically-indexed table, because technicially pairs() doesn't guarantee any order.

**Comment by Visionz1** [comment]
I will give that a try! Thank you

**Comment by jimbauwens** [comment]
Hi, the Lua sort page has a nice routine you can use for this: https://www.lua.org/pil/19.3.html

```
    function pairsByKeys (t, f)
      local a = {}
      for n in pairs(t) do table.insert(a, n) end
      table.sort(a, f)
      local i = 0      -- iterator variable
      local iter = function ()   -- iterator function
        i = i + 1
        if a[i] == nil then return nil
        else return a[i], t[a[i]]
        end
      end
      return iter
    end
```

Then do something like `for variable, _ in pairsByKeys(self.sub.variables) do` and you should be set!

**Comment by Visionz1** [comment]
Awesome! Thank you
